#' @title Visualization of Pathway Enrichment Results
#' @description The \code{plot_heat} function generates multi-panel heatmap
#'   visualizations of Gene Set Enrichment Analysis (GSEA) results, displaying
#'   normalized enrichment scores (NES), significance values, and gene ranking
#'   patterns. Each heatmap panel highlights the distribution and direction of
#'   pathway enrichment, allowing visual comparison across multiple pathway
#'   categories.
#'
#' @param seDataFgsea A \code{SummarizedExperiment} object containing:
#'   \itemize{
#'     \item \code{metadata(seDataFgsea)$cor.df}: Correlation statistics from
#'           \code{sigCor}.
#'     \item \code{metadata(seDataFgsea)$gseaResult}: GSEA result object from
#'           \code{sig2GSEA}, containing NES and p-value statistics.
#'   }
#' @param significantType Character. Type of significance metric used for
#'   filtering enriched pathways:
#'   \itemize{
#'     \item \code{"pval"} (default): Nominal p-values.
#'     \item \code{"padj"}: Adjusted p-values.
#'   }
#' @param topN Integer. Number of top significant pathways to display per
#'   category. Default is \code{10}.
#' @param pathwaysAll List. Pathway database (e.g. MSigDB collection), typically
#'   generated by splitting \code{t2g$ensembl_gene} by \code{t2g$gs_name}.
#' @param strings Character vector specifying pathway categories to visualize
#'   (e.g. \code{c("HALLMARK", "KEGG", "REACTOME")}). Default includes major
#'   MSigDB collections.
#' @param rankingMethod Character. Column name in \code{cor.df} used as ranking
#'   metric for GSEA (e.g. \code{"cor"} or \code{"pval"}). Default is
#'   \code{"cor"}.
#' @param colWidths Numeric vector of length 5 controlling the relative column
#'   widths in the multi-panel grid layout. Corresponds to
#'   \code{("NES bar", "NES", "pvalueType", "Enrichment plot", "Pathway name")}.
#'   Default is \code{c(1.5, 0.8, 1, 6, 4.5)}.
#' @param breaklineN Integer. Number of characters after which to break long
#'   pathway names into multiple lines. Default is \code{30}.
#' @param fontSize Numeric. Font size for pathway labels and annotations.
#'   Default is \code{8}.
#' @param pvalueType Character. Column name in the GSEA results used to represent
#'   statistical significance. Must be one of \code{"pvalue"},
#'   \code{"p.adjust"}, or \code{"qvalue"}. Default is \code{"pvalue"}.
#'
#' @details
#'   This function visualizes GSEA enrichment results across pathway categories
#'   using a composite heatmap layout. Each heatmap includes multiple aligned
#'   panels summarizing:
#'   \enumerate{
#'     \item Normalized enrichment scores (NES)
#'     \item Significance values (-log10 transformed)
#'     \item Enrichment score distribution
#'     \item Pathway names with leading-edge genes
#'   }
#'
#'   Color gradients represent the direction of association
#'   (\emph{red = positive}, \emph{blue = negative}).
#'   The function automatically selects top enriched pathways per collection
#'   (defined in \code{strings}) and integrates gene ranking data for each
#'   pathway set.
#'
#' @return A named list of \code{ggplot} objects. Each element corresponds to a
#'   pathway category (as defined in \code{strings}) and contains a multi-panel
#'   heatmap visualization.
#'
#' @importFrom SummarizedExperiment rowData
#' @importFrom S4Vectors metadata
#' @importFrom dplyr filter select left_join mutate arrange desc slice group_by
#'   summarize distinct
#' @importFrom cli cli_abort
#' @importFrom tibble as_tibble deframe
#' @export
#'
#' @examples
#' data("sig2Fun_result")
#' data(t2g)
#' pathwaysAll <- split(t2g$ensembl_gene, t2g$gs_name)
#' plot_heat(seDataFgsea = sig2Fun_result,
#'           strings = "HALLMARK",
#'           pathwaysAll = pathwaysAll,
#'           topN = 5)
#'
#' @note
#' Requires \pkg{ggplot2} (>= 3.5.0), \pkg{dplyr} (>= 1.1.0),
#' and \pkg{fgsea} (>= 1.26.0) for full compatibility.

# Note: Requires ggplot2 (>= 3.5.0), dplyr (>= 1.1.0), fgsea (>= 1.26.0)
plot_heat <- function(
        seDataFgsea, significantType = "pval", topN = 10, pathwaysAll,
        strings = c("GOBP", "GOCC", "GOMF", "KEGG", "REACTOME", "WP", "HALLMARK"),
        rankingMethod = "cor", colWidths = c(1.5, .8, 1, 6, 4.5),
        breaklineN = 30, fontSize = 8, pvalueType = "pvalue") {

    if (length(colWidths) != 5) {
        cli::cli_abort(
            'The {.arg colWidths} must be a vector of length 5, which controls
       the width of "NES bar", "NES", "pvalueType", "Enrichment plot", and
       "Pathway name".'
        )
    }

    match.arg(pvalueType, c("pvalue", "p.adjust", "qvalue"))

    corDf <- S4Vectors::metadata(seDataFgsea)$cor.df
    if (!(rankingMethod %in% colnames(corDf))) {
        cli::cli_abort(
            "The input {.arg rankingMethod} must be included in {.field seDataFgsea@metadata$cor.df}."
        )
    }

    resGsea <- S4Vectors::metadata(seDataFgsea)$gseaResult %>%
        tibble::as_tibble() %>%
        dplyr::slice(grep(paste(strings, collapse = "|"), ID)) %>%
        dplyr::mutate(`-log10(pvalue)` = -log10(pvalue))

    if (significantType == "pval") {
        resGsea <- resGsea %>% dplyr::filter(pvalue < 0.05)
    } else if (significantType == "padj") {
        resGsea <- resGsea %>% dplyr::filter(p.adjust < 0.05)
    }

    codingGene <- SummarizedExperiment::rowData(seDataFgsea) %>%
        as.data.frame() %>%
        dplyr::filter(gene_biotype == "protein_coding") %>%
        dplyr::select(ENSG = ensg_id, geneSymbol = gene_symbol)

    ranksDf <- corDf %>%
        dplyr::filter(!is.na(gene)) %>%
        dplyr::select(ENSG = gene, stat = dplyr::all_of(rankingMethod)) %>%
        dplyr::left_join(codingGene, by = "ENSG") %>%
        dplyr::mutate(absStat = abs(stat)) %>%
        dplyr::select(ENSG, stat) %>%
        na.omit() %>%
        dplyr::distinct() %>%
        dplyr::group_by(ENSG) %>%
        dplyr::summarize(rankingMethod = mean(as.numeric(stat))) %>%
        dplyr::filter(rankingMethod != "Inf" & rankingMethod != "-Inf") %>%
        tibble::deframe()

    tmpRes <- lapply(strings, function(str) {
        resNes <- resGsea %>% dplyr::slice(grep(str, ID))
        resNesTop <- resNes %>%
            dplyr::arrange(dplyr::desc(NES)) %>%
            dplyr::filter(NES >= 0)
        if (nrow(resNesTop) >= topN) {
            resNesTop <- resNesTop %>% dplyr::slice(seq_len(topN))
        }
        resNesBottom <- resNes %>%
            dplyr::arrange(dplyr::desc(-NES)) %>%
            dplyr::filter(NES <= 0)
        if (nrow(resNesBottom) >= topN) {
            resNesBottom <- resNesBottom %>% dplyr::slice(seq_len(topN))
        }
        resNes <- rbind(resNesTop, resNesBottom) %>%
            dplyr::arrange(dplyr::desc(NES))

        tmp <- .plotGseaTable(
            pathways = pathwaysAll[resNes$ID],
            stats = ranksDf,
            fgseaRes = resGsea,
            colWidths = colWidths,
            breaklineN = breaklineN,
            fontSize = fontSize,
            pvalueType = pvalueType
        )
        tmp
    })

    names(tmpRes) <- strings
    return(tmpRes)
}
